[package]
name = "risp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.0"
nom = "7.1"
rustyline = "12.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
